### ISSUE TITLE
No elimina las paginas virtuales

### ISSUE THREAD

**Issue by camilortte** [camilortte/ProcesosSO-java#2]
Cuando un proceso termina su ejecución las paginas en memoria virtual no son retiradas

![bug13](https://f.cloud.github.com/assets/719706/524050/d5c70fae-c0f5-11e2-8857-bb6e92b958c0.png)

**Comment by jfreddypuentes** [comment]
Esa era una pregunta que tenia, que jumm.. Ya se corrigió esta parte.
